version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: ekm-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: EkmServer
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./Ekm.Server
      dockerfile: Dockerfile
    container_name: ekm-backend
    restart: always
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/EkmServer
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 12345

  frontend:
    build:
      context: ./Ekm.Client
      dockerfile: Dockerfile
    container_name: ekm-frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "4200:80"
    volumes:
      - ./Ekm.Client:/app

volumes:
  postgres_data:
